from enum import Enum

from pydantic import BaseModel


class AiErrorCode(str, Enum):
    """Spring Boot가 분기 처리할 수 있도록 고정한 AI 오류 코드."""

    ARTWORK_CONTEXT_REQUIRED = "ARTWORK_CONTEXT_REQUIRED"
    INVALID_REQUEST = "INVALID_REQUEST"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    GEMINI_QUOTA_EXHAUSTED = "GEMINI_QUOTA_EXHAUSTED"
    GEMINI_AUTH_FAILED = "GEMINI_AUTH_FAILED"
    AI_SERVER_CONFIGURATION_ERROR = "AI_SERVER_CONFIGURATION_ERROR"
    AI_GENERATION_FAILED = "AI_GENERATION_FAILED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


class AiErrorResponse(BaseModel):
    """FastAPI가 AI 생성 실패 시 반환하는 공통 JSON 형식."""

    code: AiErrorCode
    message: str
